spring:
  application:
    name: simple-ecommerce-website

  datasource:
    url: jdbc:sqlite:/Users/mohd24s_tkd/Desktop/Database-Spring/ecommerce.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: rg.hibernate.community.dialect.SQLiteDialect
